fos_rest:
    serializer:
        serialize_null: true
    body_listener:
        enabled: true
        throw_exception_on_unsupported_content_type:  true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/auth', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
#    param_fetcher_listener: force
    view:
        view_response_listener: 'force'
        formats:
            json: true
    allowed_methods_listener: true